/* ====== Header =======
 * File: device_config.h generated by MCC
 * Purpose: header file for device_config.c
 */

#ifndef DEVICE_CONFIG_H
#define	DEVICE_CONFIG_H

#define _XTAL_FREQ 500000

#endif	/* DEVICE_CONFIG_H */
/**
 End of File
*/
