/* ====== Header =======
 * File: pin_manger.c generated by MCC
 * Author: Gavin Lyons
 * IDE: MPLAB v5.05
 * Compiler: xc8 v2.0
 * Description: see URL for full details, project 2.
 * URL: https://github.com/gavinlyonsrepo/pic_16F1619_projects
 */

#include <xc.h>
#include "pin_manager.h"
#include "stdbool.h"





void PIN_MANAGER_Initialize(void)
{
    /**
    LATx registers
    */
    LATA = 0x05;
    LATB = 0x00;
    LATC = 0x00;

    /**
    TRISx registers
    */
    TRISA = 0x32;
    TRISB = 0xF0;
    TRISC = 0xFF;

    /**
    ANSELx registers
    */
    ANSELC = 0xCF;
    ANSELB = 0xF0;
    ANSELA = 0x17;

    /**
    WPUx registers
    */
    WPUB = 0x00;
    WPUA = 0x00;
    WPUC = 0x00;
    OPTION_REGbits.nWPUEN = 1;

    /**
    ODx registers
    */
    ODCONA = 0x00;
    ODCONB = 0x00;
    ODCONC = 0x00;

    /**
    SLRCONx registers
    */
    SLRCONA = 0x37;
    SLRCONB = 0xF0;
    SLRCONC = 0xFF;





   
    
	
    RA2PPS = 0x0E;   //RA2->PWM3:PWM3OUT;    
}
  
void PIN_MANAGER_IOC(void)
{   
}

/**
 End of File
*/
